### ISSUE TITLE
Components set as NEVER

### ISSUE THREAD

**Issue by deepajrao** [OraOpenSource/apex-sert#5]
Hi Scott,

The reports include regions set as NEVER. Can these be excluded in the report ? 

Thanks,
Deepa

**Comment by DougAGault** [comment]
I think I can answer this one.

When we wrote SERT we decided to check everything no matter what the Condition was set to. This is because you should know about all possible insecurities in any and all objects in APEX regardless of whether they are rendered on the page or not.

Who is to say that someone will not go and change the condition of that object so that it does render. It is better to have checked the object and know of the possible insecurity than not to have checked it at all.

In my mind (and Scott can definitely weigh in) it would be better to KNOW that the objects are there and create an Exception for any insecurity rather than ignoring them all together. The justification for the exception could be as simple as "Condition set to Never".  Then when the object is edited (say to remove the condition), the Exception would become stale an the potential insecurity would again be brought to your attention.

Hope this helps

Doug Gault

**Comment by deepajrao** [comment]
Thanks Doug for the response. I will use exceptions here
